apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-koala
  namespace: drone
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-koala
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-koala
    spec:
      serviceAccountName: drone-koala-runner
      containers:
        - name: {{ .Release.Name }}-koala
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- range $key, $value := index .Values "koala-env" }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-env