apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-runner-full-binding
  namespace: drone
subjects:
  - kind: ServiceAccount
    name: drone-koala-runner
    namespace: drone
roleRef:
  kind: Role
  name: drone-runner-full
  apiGroup: rbac.authorization.k8s.io