apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-runner-full
  namespace: drone
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - pods
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - watch
      - update
      - patch