apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-drone-env
type: Opaque
stringData:
  {{- range $key, $value := .Values.drone.secretEnv }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}