apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.drone.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.drone.service.port }}
      targetPort: {{ .Values.drone.service.targetPort }}