controller:
  kind: DaemonSet
  hostNetwork: true
  daemonset:
    useHostPort: true
  service:
    enabled: false
    type: ""
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  # extraArgs:
  #   enable-ssl-passthrough: ""

  config:
    use-forwarded-headers: "true"
    proxy-body-size: "64m"

admissionWebhooks:
  enabled: true

rbac:
  create: true

defaultBackend:
  enabled: true

metrics:
  enabled: false