apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.osrm.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.osrm.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http