koala: 
  web:
    replicaCount: 2
    image:
      repository: osdp25w/koala
      tag: latest
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
      targetPort: 8000
    ingress:
      enabled: true
      className: nginx
      host: koala.osdp25w.xyz
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
    env: 
      ENV: staging


  mqtt:
    replicaCount: 1
    image:
      repository: osdp25w/koala
      tag: latest
      pullPolicy: Always
    env: 
      ENV: staging

  celery:
    beat:
      replicaCount: 1
      image:
        repository: osdp25w/koala
        tag: latest
        pullPolicy: Always
      env: 
        ENV: staging
    
    iot_default_worker:
      replicaCount: 1
      image:
        repository: osdp25w/koala
        tag: latest
        pullPolicy: Always
      env: 
        ENV: staging
      queue: "iot_default_q"
      concurrency: 4
    
    bike_realtime_status_worker:
      replicaCount: 1
      image:
        repository: osdp25w/koala
        tag: latest
        pullPolicy: Always
      env: 
        ENV: staging
      queue: "bike_realtime_status_q"
      concurrency: 4
    
    bike_error_log_worker:
      replicaCount: 1
      image:
        repository: osdp25w/koala
        tag: latest
        pullPolicy: Always
      env: 
        ENV: staging
      queue: "bike_error_log_q"
      concurrency: 4
    
    statistics_worker:
      replicaCount: 1
      image:
        repository: osdp25w/koala
        tag: latest
        pullPolicy: Always
      env: 
        ENV: staging
      queue: "statistics_q"
      concurrency: 4