apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  10-defaults.conf: |
    # MQTT configuration
    mqtt.allow_anonymous = false
    mqtt.vhost = /
    mqtt.exchange = amq.topic
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch = 10

    # MQTT configuration
    mqtt.listeners.tcp.default = {{ .Values.rabbitmq.service.ports.mqtt }}
    
    # MQTT over SSL configuration
    {{- if .Values.rabbitmq.tls.enabled }}
    mqtt.listeners.ssl.default = {{ .Values.rabbitmq.serviceMQTTS.ports.mqtts }}
    ssl_options.certfile = {{ .Values.rabbitmq.tls.mountPath }}/{{ .Values.rabbitmq.tls.certFile }}
    ssl_options.keyfile = {{ .Values.rabbitmq.tls.mountPath }}/{{ .Values.rabbitmq.tls.keyFile }}
    ssl_options.cacertfile = {{ .Values.rabbitmq.tls.mountPath }}/{{ .Values.rabbitmq.tls.caFile }}
    ssl_options.verify = verify_peer
    ssl_options.fail_if_no_peer_cert = true
    {{- end }}
    management.tcp.port = 15672

    # Logging
    log.console = true
    log.console.level = info

    # Memory and disk thresholds
    vm_memory_high_watermark.relative = 0.6
    disk_free_limit.absolute = 2GB

  enabled_plugins: |
    [{{ range $i, $plugin := .Values.rabbitmq.plugins }}{{if $i}},{{end}}{{ $plugin }}{{ end }}].