apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.rabbitmq.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.ports.amqp }}
      targetPort: amqp
      protocol: TCP
    - name: management
      port: 15672
      targetPort: management
      protocol: TCP
    - name: mqtt
      port: {{ .Values.rabbitmq.service.ports.mqtt }}
      targetPort: mqtt
      protocol: TCP
  selector:
    app: {{ .Release.Name }} 